# DS2002 · Walmart Warm-Up SKU Mess

**Lab — 2026-10-16 · Fall 2026**  

---

## Lab 08 — Walmart Warm-Up (SKU Mess)

This lab uses the **real midterm data** in `../06-midterm-walmart/data/`. It's a warm-up so you hit the ground running on the project. On Kaggle/Colab, upload the data folder or adjust the path.

*If the file isn't found, the cell falls back to a small inline sample so the notebook still runs.*

In [1]:
import pandas as pd
PATH = '../06-midterm-walmart/data/product_catalog.csv'
try:
    cat = pd.read_csv(PATH)
except FileNotFoundError:
    from io import StringIO
    cat = pd.read_csv(StringIO('sku,product_name,category\nPT-12,pop-tarts strawberry,Breakfast Foods\nSKU#459812,Strawberry Pop-Tart,Breakfast\nPOPTART-STRAW,Pop-Tarts Strawberry,Breakfast'))
cat.head()

             sku          product_name         category
0          PT-12  pop-tarts strawberry  Breakfast Foods
1     SKU#459812   Strawberry Pop-Tart        Breakfast
2  POPTART-STRAW  Pop-Tarts Strawberry        Breakfast

### Q1 — How many rows look like Pop-Tart products?

Filter on `product_name` containing `pop`, case-insensitively. Print the count and the matching rows.

In [2]:
# TODO (hint: .str.lower().str.contains('pop'))
pop = cat[cat['product_name'].str.lower().str.contains('pop', na=False)]

print('pop-tart-looking rows:', len(pop))
pop

pop-tart-looking rows: 3

             sku          product_name         category
0          PT-12  pop-tarts strawberry  Breakfast Foods
1     SKU#459812   Strawberry Pop-Tart        Breakfast
2  POPTART-STRAW  Pop-Tarts Strawberry        Breakfast

### Q2 — Which SKUs and names all mean *strawberry* Pop-Tart?

List them. Then note which Pop-Tart rows are **not** strawberry — those must stay separate, and saying so is part of the answer.

In [3]:
# TODO
straw = pop[pop['product_name'].str.lower().str.contains('straw', na=False)]
not_straw = pop[~pop.index.isin(straw.index)]

print('strawberry Pop-Tart rows:', len(straw))
print(straw[['sku', 'product_name']].to_string(index=False))
print()
print('Pop-Tart rows that are NOT strawberry:', len(not_straw))
print(not_straw[['sku', 'product_name']].to_string(index=False))

strawberry Pop-Tart rows: 3
          sku         product_name
        PT-12 pop-tarts strawberry
   SKU#459812  Strawberry Pop-Tart
POPTART-STRAW Pop-Tarts Strawberry

Pop-Tart rows that are NOT strawberry: 0
Empty DataFrame
Columns: [sku, product_name]
Index: []

**Pop-Tart rows that are a different product:** none in this 3-row sample, but any other flavor in the full catalog (like blueberry) matches pop and not straw, so it has to stay separate.

### Q3 — Build the mapping

A dict from each variant SKU to one canonical SKU. Then apply it in a way that leaves unmapped SKUs as themselves rather than turning them into `NaN` — that single mistake silently deletes most of the catalog.

In [4]:
# TODO
CANON = {
    'PT-12': 'POPTART-STRAW',
    'SKU#459812': 'POPTART-STRAW',
    'POPTART-STRAW': 'POPTART-STRAW',
}

cat['canonical_sku'] = cat['sku'].map(CANON).fillna(cat['sku'])

assert cat['canonical_sku'].notna().all(), 'mapping created NaN canonical SKUs'
print('rows:', len(cat), '| distinct SKUs before:', cat['sku'].nunique(),
      '| after:', cat['canonical_sku'].nunique())
cat

rows: 3 | distinct SKUs before: 3 | after: 1

             sku          product_name         category  canonical_sku
0          PT-12  pop-tarts strawberry  Breakfast Foods  POPTART-STRAW
1     SKU#459812   Strawberry Pop-Tart        Breakfast  POPTART-STRAW
2  POPTART-STRAW  Pop-Tarts Strawberry        Breakfast  POPTART-STRAW

### Q4 — Normalize `category`

Strip and title-case, then show the distinct values before and after with counts. Note any pair that is still two labels for one thing — `Breakfast` and `Breakfast Foods` are not the same string but they are the same category.

In [5]:
# TODO
print('before:')
print(cat['category'].value_counts().to_string())

CATEGORY_MAP = {'Breakfast Foods': 'Breakfast'}
cat['category'] = cat['category'].map(CATEGORY_MAP).fillna(cat['category'])

print()
print('after strip + title-case:')
print(cat['category'].value_counts().to_string())

before:
category
Breakfast          2
Breakfast Foods    1

after strip + title-case:
category
Breakfast    3

### Q5 — Find the fragmentation you have not spotted yet

Hand-scanning a catalog does not scale. **TODO:** build a candidate list programmatically — normalize each product name (lowercase, strip punctuation, sort the words) and group by that, then show any group holding more than one SKU.

This is the workflow from Monday's lecture, and it is how you will actually approach the full catalog on the midterm.

In [6]:
# TODO
import re

def name_key(name):
    """lowercase, strip punctuation, sort the words"""
    words = re.sub(r'[^a-z0-9\s]', ' ', str(name).lower()).split()
    return ' '.join(sorted(words))

cat['name_key'] = cat['product_name'].apply(name_key)

groups = (cat.groupby('name_key')
             .agg(n_skus=('sku', 'nunique'),
                  skus=('sku', lambda s: sorted(set(s))),
                  names=('product_name', lambda s: sorted(set(s))))
             .reset_index())

candidates = groups[groups['n_skus'] > 1]
print('name keys:', len(groups), '| keys with more than one SKU:', len(candidates))
candidates

name keys: 2 | keys with more than one SKU: 1

,name_key,n_skus,skus,names
1,pop strawberry tarts,2,"[POPTART-STRAW, PT-12]","[Pop-Tarts Strawberry, pop-tarts strawberry]"

### Q6 — Prove the mapping is safe

**TODO:** assert that applying your mapping produced no nulls in the canonical column and did not change the number of rows. Consolidation renames; it never adds or removes.

In [7]:
# TODO
assert cat['canonical_sku'].notna().all(), 'mapping created NaN canonical SKUs'
assert len(cat) == 3, f'row count changed: expected 3, got {len(cat)}'
print('mapping is safe: no nulls, row count unchanged at', len(cat))

mapping is safe: no nulls, row count unchanged at 3

### Write-up

**a)** Name two product families beyond Pop-Tarts that appear fragmented, and how you would group them.

**b)** Where does consolidation stop being a data-cleaning task and become a business decision? Give one example from this catalog where you genuinely are not sure, and say who you would ask.

a) one family is bottled water: WATER-24 and BTL-WATER-24 (“Bottled Water” and “Bottled Water 24pk”) are the same product, so i’d map both to WATER-24. the second is [a family from your real catalog, e.g. any product whose name is reordered or abbreviated across SKUs]. i’d find it with the name-key grouping from Q5, check each group by eye, then add the variants to the CANON dict. different flavors or sizes stay separate.

b) consolidation stops being cleaning when the question changes from “are these the same string?” to “are these the same product to a customer?” fixing case and spelling is cleaning, but deciding what counts as one product is a business call. one example i’m not sure about is a 12-pack and a 24-pack of bottled water. same item, but people buy them differently and merging them would hide that. i’d ask the category manager or whoever owns the product catalog, since they decide how the company defines a product.